### ISSUE TITLE
Pet Owner

### ISSUE THREAD

**Issue by InassTubail** [InassTubail/AniFlixAssignment#1]
**As a new user I go to the platform and watch a video**

Acceptance Criteria :
- [ ]  As new pet owner, I want to sign up as a pet to the platform as pet owner user.
- [ ] As new pet owner, I want to be able to sign in the website using log in credentials. 
- [ ] As new pet owner, I want to view home page so that i can find some informative videos ,view more videos and see "charity advertisement " section  .
- [ ] As new pet owner, I want to be able to save some videos.
- [ ] As new pet owner, I want to view my saved videos.
- [ ] As new pet owner, I want to edit  my profile information.
- [ ] As new pet owner, I want to be able to see the profile of 'charity user' to contact with him.
- [ ] As new pet owner, I want to be able to log out from the system
