### ISSUE TITLE
sign up as owner pet 

### ISSUE THREAD

**Issue by InassTubail** [InassTubail/AniFlixAssignment#2]
**As new pet owner, I want to sign up as a pet to the platform as pet owner user.**
Relates #1
Acceptance criteria:
- [ ] As new user, I want to sign up as pet owner by clicking on sign up pet owner button .
- [ ] After clicking sign up button, I should be redirected to another page that contains a form allowing me to add the following credentials:
* Username 
* Email Address
* Password 
* Confirm Password 
* Phone Number  
and click sign up button.
- [ ] The system notifies me that it sent an email to confirm my new account containing re directional link to the website with welcome message.
