### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by InassTubail** [InassTubail/AniFlixAssignment#3]
**As new pet owner, I want to be able to sign in the website using log in credentials.**
relates #1 
Acceptance Criteria :
- [ ] If I have account I want to be able to sign in using my credentials : 
*  Username
* Password
- [ ] If one of my credentials is wrong, the system should display warning message telling me one of my credentials is wrong.
- [ ] When all my credentials is correct, the system should redirect me to the home page.
