### ISSUE TITLE
View home page

### ISSUE THREAD

**Issue by InassTubail** [InassTubail/AniFlixAssignment#4]
**As new pet owner, I want to view home page so that i can find some informative videos ,view more videos and see "charity advertisement " section .**
relates #1
acceptance criteria :
- [ ] After I sign in, the system redirect me to the home page, which contains some videos to help owners pet how to look after their pets and increase their awareness of animal rights issues 
and charity advertisements .
- [ ] The home page should allow me to go to my profile.
- [ ] The home page should contain a search bar that allow users to search for specific videos .
- [ ] I can click on any advertisement and see some details about it.
