### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by InassTubail** [InassTubail/AniFlixAssignment#5]
As new pet owner, I want to open my profile.
relates #1
acceptance criteria :
 - [ ] After I sign in, I should be able view my profile page  .
-  [ ] The profile page should display all my saved videos .
- [ ] The profile page should allow me to edit some of my information, such like username.
